var AUTHORS=''

use import="packages\GitTagVersion.Console.0.2.0-pre-0002\tools\sake\gittagversion.shade"
@{
	var versionInfo=GitTagVersion();
	var VERSION = versionInfo["AssemblyVersion"];
	var FULL_VERSION = versionInfo["VersionWithPreReleaseV1"];
}
log info="  semversion: ${versionInfo["FullVersion"]}"

use-standard-lifecycle
use-nsemversion-goals features="xunit2,nuget"
