var AUTHORS=''

use import="packages\GitTagVersion.Console.0.2.0\tools\sake\gittagversion.shade"
@{
	var versionInfo=GitTagVersion();
	var VERSION = versionInfo["Code.AssemblyVersion"];
	var FULL_VERSION = versionInfo["SemVer1.VersionWithPreRelease"];
}
log info="  semversion: ${versionInfo["SemVer2.FullVersion"]}"

use-standard-lifecycle
use-nsemversion-goals features="xunit2,nuget"
